# Generated by Django 6.0.2 on 2026-04-22 17:31

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.RoleAwareUserManager()),
            ],
        ),
    ]
