# Generated by Django 6.0.2 on 2026-04-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('community_group', 'Community Group'), ('restaurant', 'Restaurant')], default='individual', max_length=30),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='address_line1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='institutional_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
