# Generated by Django 6.0.2 on 2026-03-25 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability_status',
            field=models.CharField(choices=[('in_season', 'In Season'), ('year_round', 'Available Year-Round'), ('out_of_season', 'Out of Season'), ('unavailable', 'Unavailable')], default='year_round', help_text='Controls whether customers should see this product.', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_warning_level',
            field=models.PositiveIntegerField(default=5, help_text='Low stock alert threshold for this product.'),
        ),
        migrations.CreateModel(
            name='ProductInventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_stock', models.IntegerField(default=0)),
                ('new_stock', models.IntegerField(default=0)),
                ('old_availability_status', models.CharField(blank=True, max_length=30)),
                ('new_availability_status', models.CharField(blank=True, max_length=30)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_changes_made', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_history', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
