# Generated by Django 6.0.2 on 2026-03-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_organic',
            field=models.BooleanField(default=False, help_text='Tick if this product is organically certified.'),
        ),
    ]
