# Generated by Django 6.0.2 on 2026-03-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_availability_status_and_more'),
        ('catalog', '0002_product_is_organic'),
    ]

    operations = [
    ]
