# Generated by Django 6.0.2 on 2026-03-26 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_merge_20260326_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('each', 'Each'), ('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Litre'), ('ml', 'Millilitre')], default='each', help_text='How this product is sold.', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='How much stock is available right now.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_warning_level',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Low stock alert threshold for this product.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productinventoryhistory',
            name='new_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productinventoryhistory',
            name='old_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
