# Generated by Django 6.0.2 on 2026-04-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_unit_alter_product_slug_alter_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_surplus',
            field=models.BooleanField(default=False, help_text='Mark this product as a last-minute surplus deal.'),
        ),
        migrations.AddField(
            model_name='product',
            name='surplus_discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage for surplus deals.'),
        ),
        migrations.AddField(
            model_name='product',
            name='surplus_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='surplus_note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
