# Generated by Django 6.0.2 on 2026-04-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_is_surplus_product_surplus_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_before_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('each', 'Each'), ('head', 'Head'), ('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Litre'), ('ml', 'Millilitre')], default='each', help_text='How this product is sold.', max_length=10),
        ),
    ]
