# Generated by Django 6.0.3 on 2026-05-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_add_marketplace_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Low stock alert threshold for this product.', max_digits=10),
        ),
    ]
