services:
  mongodb:
    image: mongo:7.0              # this is MongoDB (the database server)
    container_name: brfn_mongodb
    ports:
      - "27017:27017"           # Django app connect via localhost
    volumes:
      - mongo_data:/data/db     # keeps data saved even after restart

volumes:
  mongo_data:
