services:
  web:
    build: ./backend
    container_name: brfn_web
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: brfn_db
      POSTGRES_USER: brfn_user
      POSTGRES_PASSWORD: brfn_password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: brfn_db
      POSTGRES_USER: brfn_user
      POSTGRES_PASSWORD: brfn_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
