# Generated by Django 6.0.2 on 2026-03-26 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_unit_alter_product_slug_alter_product_stock_and_more'),
        ('orders', '0003_order_is_recurring_instance_recurringorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='recurringorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_items', to='catalog.product'),
        ),
    ]
