# Generated by Django 6.0.2 on 2026-02-25 18:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('provider', models.CharField(default='manual', help_text='Payment provider name, e.g. stripe, paypal, manual.', max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount charged (snapshot).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='GBP', help_text='Currency code, e.g. GBP.', max_length=10)),
                ('provider_reference', models.CharField(blank=True, help_text='Transaction id from the payment provider.', max_length=120)),
                ('raw_response', models.JSONField(blank=True, help_text='Optional provider response data for debugging.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('gross_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('commission_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payout_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('paid', 'Paid')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('producer', 'period_start', 'period_end'), name='uniq_settlement_producer_period')],
            },
        ),
    ]
